name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.1'

      - name: Print Go version
        run: go version

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install golangci-lint v1.64.6
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/v1.64.6/golangci-lint-1.64.6-linux-amd64.tar.gz | tar -xz
          sudo mv golangci-lint-1.64.6-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run ./...

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...