name: Build and Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'  # triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm]
        exclude:
          - goos: windows
            goarch: arm  # unsupported combo
          - goos: darwin
            goarch: arm

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go 1.24.1
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Build binary and create zip
        run: |
          mkdir -p dist
          output_name="dependency-validator-${{ matrix.goos }}-${{ matrix.goarch }}"
          binary_name="$output_name"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            binary_name="${binary_name}.exe"
          fi

          # Build the binary (replace '.' if your main code is in a subfolder)
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$binary_name" ./cmd/main.go

          # Zip the binary into dist/
          zip -j "dist/${output_name}.zip" "$binary_name"

      - name: Upload zipped binary
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/dependency-validator-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download zipped binaries (linux amd64)
        uses: actions/download-artifact@v4
        with:
          name: release-linux-amd64
          path: dist

      - name: Download zipped binaries (darwin amd64)
        uses: actions/download-artifact@v4
        with:
          name: release-darwin-amd64
          path: dist

      - name: Download zipped binaries (windows amd64)
        uses: actions/download-artifact@v4
        with:
          name: release-windows-amd64
          path: dist

      - name: Download zipped binaries (linux arm)
        uses: actions/download-artifact@v4
        with:
          name: release-linux-arm
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}