name: Build and Release

on:
  push:
    tags:
      - 'v*' # e.g., v1.0.0

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm]
        exclude:
          - goos: windows
            goarch: arm # unsupported combination

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build binary and zip
        run: |
          mkdir -p dist
          output_name="myapp-${{ matrix.goos }}-${{ matrix.goarch }}"
          binary_name="$output_name"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            binary_name="${binary_name}.exe"
          fi

          # Compile binary
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o "$binary_name" .

          # Zip the binary
          zip_file="dist/${output_name}.zip"
          zip -j "$zip_file" "$binary_name"

      - name: Upload zipped artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-zips
          path: dist/*.zip

  release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download zipped artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-zips
          path: dist

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}